dist: xenial

os:
    - linux
    #- osx 
    - windows

env:
    global:
        - VENV_CACHE=$HOME/.cache/venv
    matrix:
        - PYTHON_REV=3.7.4
#        - PYTHON_REV=3.6.8
#         - BLENDER_VERSION="2.79-nightly"
#         - BLENDER_VERSION="2.80-nightly"

language: bash
# python:
#     - 3.6

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${VENV_CACHE}

before_install:
      - mkdir -p ${VENV_CACHE}
      - source get_python.sh
      - ls ${VENV_CACHE}
#     - mkdir -p ${BLENDER_CACHE}
#     - ls ${BLENDER_CACHE}
#     - pip3 install -r scripts/requirements.txt --upgrade
#     - yolk -l

install:
    - pwd
    - python --version
    - which python
#     - cd $TRAVIS_BUILD_DIR
#     - python3 --version
#     - python3 scripts/get_blender.py ${BLENDER_VERSION}

script:
    - pwd
#     - cd ${TRAVIS_BUILD_DIR}
#     - ../blender-${BLENDER_VERSION}/blender --version
#     - cat tests/lwo_phobos/test_load_lwo_phobos.py
#     - python3 scripts/run_blender.py ${BLENDER_VERSION}

#after_success:
#    - codecov -f tests_output/coverage.xml

notifications:
    email:
        on_success: change
        on_failure: always
