dist: xenial

language: bash

jobs:
    include:
        - os: linux
        - os: windows
        - os: osx
          rvm: 2.63
# os:
#     - linux
#     - osx 
#     - windows

env:
    global:
        - VENV_CACHE=$HOME/.cache/venv
        - PYTHON_REV=3.7.5
#     matrix:
#         - PYTHON_REV=3.6.8
#         - PYTHON_REV=3.8.0

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${VENV_CACHE}

before_install:
      - mkdir -p ${VENV_CACHE}
      - source get_python.sh

install:
    - which python
    - which pip
    - which yolk

script:
    - python --version

notifications:
    email:
        on_success: change
        on_failure: always
