dist: xenial

os:
    #- linux
    - osx 
    #- windows

env:
    global:
        - VENV_CACHE=$HOME/.cache/venv
    matrix:
#        - PYTHON_REV=3.8.0
        - PYTHON_REV=3.7.4
#        - PYTHON_REV=3.6.8

language: bash

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${VENV_CACHE}

before_install:
      - mkdir -p ${VENV_CACHE}
      - source get_python.sh

install:
    - which python

script:
    - python --version

notifications:
    email:
        on_success: change
        on_failure: always
