dist: xenial

os:
    #- linux
    - osx 
    #- windows

env:
    global:
        - VENV_CACHE=$HOME/.cache/venv
    matrix:
#         - PYTHON_REV=3.4.8
#         - PYTHON_REV=3.5.7
        - PYTHON_REV=3.6.8
#         - PYTHON_REV=3.7.5
#         - PYTHON_REV=3.8.0

language: bash

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${VENV_CACHE}

before_install:
      - mkdir -p ${VENV_CACHE}
      - source get_python.sh

install:
    - which python
    - which pip
    - which yolk

script:
    - python --version

notifications:
    email:
        on_success: change
        on_failure: always
