dist: xenial

os:
    - linux
    - osx 
    - windows #No python support

# env:
#     global:
#         - BLENDER_CACHE=$HOME/.cache/blender
#     matrix:
#         - BLENDER_VERSION="2.78c"
# #        - BLENDER_VERSION="2.79b"
#         - BLENDER_VERSION="2.79-nightly"
#         - BLENDER_VERSION="2.80-nightly"

language: bash
# python:
#     - 3.7

cache:
    apt: true
#     directories:
#         - $HOME/.cache/pip
#         - ${BLENDER_CACHE}
# 
# addons:
#     apt:
#         packages:
#             - blender
# 
# git:
#     submodules:
#         false

before_install:
      source get_python
#     - mkdir -p ${BLENDER_CACHE}
#     - ls ${BLENDER_CACHE}
#     - pip3 install -r scripts/requirements.txt --upgrade
#     - yolk -l

install:
    - pwd
#     - cd $TRAVIS_BUILD_DIR
#     - python3 --version
#     - python3 scripts/get_blender.py ${BLENDER_VERSION}

script:
    - pwd
#     - cd ${TRAVIS_BUILD_DIR}
#     - ../blender-${BLENDER_VERSION}/blender --version
#     - cat tests/lwo_phobos/test_load_lwo_phobos.py
#     - python3 scripts/run_blender.py ${BLENDER_VERSION}

#after_success:
#    - codecov -f tests_output/coverage.xml

notifications:
    email:
        on_success: change
        on_failure: always
